<?php
namespace frontend\widgets;
use yii\base\Widget;
class CategorySeoText extends Widget
{
    public $category;
    /**
     * Widget options
     * @var array
     */
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub


    }

    public function run()
    {
        return $this->render('categorySeoText', [
            'category' => $this->category
        ]);
    }
}